import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.dailyEntry": "Daily Entry",
    "nav.weeklyView": "Weekly View",
    "nav.approvals": "Approvals",
    "nav.reports": "Reports",
    "nav.settings": "Settings",
    "nav.help": "Help",
    "nav.logout": "Log out",
    "nav.myAccount": "My Account",
    "nav.profile": "Profile",
    "nav.team": "Team",
    "nav.menu": "Menu",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.hoursThisWeek": "Hours This Week",
    "dashboard.ofTarget": "of 40h target",
    "dashboard.vsLastWeek": "vs last week",
    "dashboard.billableHours": "Billable Hours",
    "dashboard.billableRate": "billable rate",
    "dashboard.pendingApprovals": "Pending Approvals",
    "dashboard.awaitingReview": "Awaiting review",
    "dashboard.approvedTimesheets": "Approved Timesheets",
    "dashboard.thisMonth": "This month",
    "dashboard.vsLastMonth": "vs last month",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.weeklyHours": "Weekly Hours",
    "dashboard.projectsThisWeek": "Projects This Week",
    "dashboard.total": "total",
    "dashboard.upcomingDeadlines": "Upcoming Deadlines",
    "dashboard.dueToday": "Due today",
    "dashboard.daysLeft": "days left",
    "dashboard.billable": "Billable",
    "dashboard.nonBillable": "Non-billable",
    
    // Activity types
    "activity.timeLogged": "Time Logged",
    "activity.timesheetApproved": "Timesheet Approved",
    "activity.timesheetSubmitted": "Timesheet Submitted",
    "activity.entryRequiresChanges": "Entry Requires Changes",
    
    // Daily Entry
    "daily.title": "Daily Time Entry",
    "daily.subtitle": "Log your hours for the day",
    "daily.timerRunning": "Timer running",
    "daily.startTimer": "Start a timer",
    "daily.start": "Start",
    "daily.stop": "Stop",
    "daily.copyPreviousDay": "Copy Previous Day",
    "daily.dailyTotal": "Daily Total",
    "daily.project": "Project",
    "daily.description": "Description",
    "daily.startTime": "Start",
    "daily.endTime": "End",
    "daily.duration": "Duration",
    "daily.billableToggle": "Billable",
    "daily.selectProject": "Select project",
    "daily.whatDidYouWork": "What did you work on?",
    "daily.addTimeEntry": "Add Time Entry",
    "daily.entriesLogged": "entries logged for",
    "daily.saveAsDraft": "Save as Draft",
    "daily.submitForApproval": "Submit for Approval",
    
    // Weekly Entry
    "weekly.title": "Weekly Time Entry",
    "weekly.subtitle": "View and edit your weekly hours",
    "weekly.week": "Week",
    "weekly.today": "Today",
    "weekly.copyWeek": "Copy Week",
    "weekly.weekTotal": "Week Total",
    "weekly.addProject": "Add Project",
    "weekly.dailyTotal": "Daily Total",
    "weekly.billableHours": "Billable Hours",
    "weekly.ofTotal": "of total",
    "weekly.targetProgress": "Target Progress",
    "weekly.status": "Status",
    "weekly.pendingApproval": "Pending Approval",
    "weekly.submitted": "Submitted",
    "weekly.projects": "projects",
    "weekly.logged": "logged",
    "weekly.allEntriesSaved": "All entries saved automatically",
    "weekly.submitWeek": "Submit Week",
    
    // Approvals
    "approvals.title": "Approval Queue",
    "approvals.subtitle": "timesheets awaiting your review",
    "approvals.searchPlaceholder": "Search by name or project...",
    "approvals.allStatus": "All Status",
    "approvals.pending": "Pending",
    "approvals.approved": "Approved",
    "approvals.rejected": "Rejected",
    "approvals.selected": "selected",
    "approvals.approveAll": "Approve All",
    "approvals.rejectAll": "Reject All",
    "approvals.employee": "Employee",
    "approvals.period": "Period",
    "approvals.hours": "Hours",
    "approvals.projects": "Projects",
    "approvals.actions": "Actions",
    "approvals.billable": "billable",
    "approvals.timesheetDetails": "Timesheet Details",
    "approvals.reviewSubmission": "Review the complete timesheet submission",
    "approvals.totalHours": "Total Hours",
    "approvals.close": "Close",
    "approvals.reject": "Reject",
    "approvals.approve": "Approve",
    
    // Reports
    "reports.title": "Reports",
    "reports.subtitle": "Analyze your time tracking data",
    "reports.overview": "Overview",
    "reports.byProject": "By Project",
    "reports.byTeamMember": "By Team Member",
    "reports.byClient": "By Client",
    "reports.allProjects": "All Projects",
    "reports.totalHours": "Total Hours",
    "reports.vsPreviousPeriod": "vs previous period",
    "reports.billableHours": "Billable Hours",
    "reports.billableRate": "billable rate",
    "reports.teamMembers": "Team Members",
    "reports.activeThisPeriod": "Active this period",
    "reports.avgUtilization": "Avg. Utilization",
    "reports.vsTarget": "vs target",
    "reports.monthlyTrends": "Monthly Trends",
    "reports.timeByProject": "Time by Project",
    "reports.teamBreakdown": "Team Breakdown",
    "reports.teamMember": "Team Member",
    "reports.utilization": "Utilization",
    "reports.progress": "Progress",
    
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account and preferences",
    "settings.profile": "Profile",
    "settings.profileDesc": "Your personal information",
    "settings.preferences": "Preferences",
    "settings.preferencesDesc": "Customize your experience",
    "settings.account": "Account",
    "settings.accountDesc": "Security and authentication",
    "settings.appSettings": "App Settings",
    "settings.appSettingsDesc": "Application configuration",
    "settings.firstName": "First Name",
    "settings.lastName": "Last Name",
    "settings.email": "Email Address",
    "settings.jobTitle": "Job Title",
    "settings.department": "Department",
    "settings.phone": "Phone Number",
    "settings.timezone": "Timezone",
    "settings.dateFormat": "Date Format",
    "settings.timeFormat": "Time Format",
    "settings.weekStartsOn": "Week Starts On",
    "settings.monday": "Monday",
    "settings.sunday": "Sunday",
    "settings.notifications": "Notifications",
    "settings.emailNotifications": "Email Notifications",
    "settings.emailNotificationsDesc": "Receive email updates about your timesheets",
    "settings.reminderNotifications": "Reminder Notifications",
    "settings.reminderNotificationsDesc": "Get reminded to submit your timesheet",
    "settings.approvalNotifications": "Approval Notifications",
    "settings.approvalNotificationsDesc": "Notify when timesheets are approved or rejected",
    "settings.changePassword": "Change Password",
    "settings.currentPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmPassword": "Confirm New Password",
    "settings.updatePassword": "Update Password",
    "settings.twoFactorAuth": "Two-Factor Authentication",
    "settings.twoFactorAuthDesc": "Add an extra layer of security to your account",
    "settings.enable2FA": "Enable 2FA",
    "settings.activeSessions": "Active Sessions",
    "settings.activeSessionsDesc": "Manage your logged in devices",
    "settings.viewSessions": "View Sessions",
    "settings.defaultProject": "Default Project",
    "settings.selectDefault": "Select default",
    "settings.defaultBillable": "Default Billable Status",
    "settings.billableByDefault": "Billable by default",
    "settings.billableByDefaultDesc": "New time entries are billable by default",
    "settings.workingHours": "Working Hours",
    "settings.hoursPerDay": "Hours per Day",
    "settings.hoursPerWeek": "Hours per Week",
    "settings.autoSave": "Auto-save",
    "settings.autoSaveDesc": "Automatically save time entries as you type",
    "settings.saveChanges": "Save Changes",
    "settings.dangerZone": "Danger Zone",
    "settings.deleteAccount": "Delete Account",
    "settings.deleteAccountDesc": "Permanently delete your account and all data",
    
    // Help
    "help.title": "Help Center",
    "help.subtitle": "Find answers and get support",
    "help.searchPlaceholder": "Search for help articles...",
    "help.quickLinks": "Quick Links",
    "help.gettingStarted": "Getting Started",
    "help.gettingStartedDesc": "Learn the basics of time tracking",
    "help.videoTutorials": "Video Tutorials",
    "help.videoTutorialsDesc": "Watch step-by-step guides",
    "help.keyboard": "Keyboard Shortcuts",
    "help.keyboardDesc": "Work faster with shortcuts",
    "help.apiDocs": "API Documentation",
    "help.apiDocsDesc": "Integrate with other tools",
    "help.faq": "Frequently Asked Questions",
    "help.contactSupport": "Contact Support",
    "help.contactSupportDesc": "Can't find what you're looking for? Our support team is here to help.",
    "help.name": "Your Name",
    "help.emailAddress": "Email Address",
    "help.subject": "Subject",
    "help.selectTopic": "Select a topic",
    "help.generalQuestion": "General Question",
    "help.technicalIssue": "Technical Issue",
    "help.billingInquiry": "Billing Inquiry",
    "help.featureRequest": "Feature Request",
    "help.message": "Message",
    "help.describeIssue": "Describe your issue or question...",
    "help.sendMessage": "Send Message",
    
    // FAQ
    "faq.howToLog": "How do I log my time?",
    "faq.howToLogAnswer": "You can log time in two ways: 1) Use the Daily Entry page to manually enter your hours with start/end times or duration. 2) Use the timer feature to track time in real-time. Simply select a project, add a description, and click Start.",
    "faq.editEntry": "Can I edit a submitted timesheet?",
    "faq.editEntryAnswer": "Once a timesheet is submitted for approval, you cannot edit it directly. However, you can request your manager to reject it, which will return it to draft status for editing. Alternatively, contact your administrator for assistance.",
    "faq.billableVsNon": "What's the difference between billable and non-billable hours?",
    "faq.billableVsNonAnswer": "Billable hours are time spent on client work that can be invoiced. Non-billable hours include internal meetings, training, administrative tasks, and other activities that cannot be charged to clients.",
    "faq.approvalTime": "How long does approval take?",
    "faq.approvalTimeAnswer": "Approval times vary by organization. Typically, managers review timesheets within 1-3 business days. You'll receive a notification when your timesheet is approved or if changes are requested.",
    "faq.exportData": "Can I export my time data?",
    "faq.exportDataAnswer": "Yes! Go to the Reports page and use the export buttons to download your data in PDF, Excel, or CSV format. You can filter by date range, project, or team member before exporting.",
    
    // Common
    "common.search": "Search",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.logTime": "Log Time",
  },
  de: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.dailyEntry": "Tageseintrag",
    "nav.weeklyView": "Wochenansicht",
    "nav.approvals": "Genehmigungen",
    "nav.reports": "Berichte",
    "nav.settings": "Einstellungen",
    "nav.help": "Hilfe",
    "nav.logout": "Abmelden",
    "nav.myAccount": "Mein Konto",
    "nav.profile": "Profil",
    "nav.team": "Team",
    "nav.menu": "Menü",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Willkommen zurück",
    "dashboard.hoursThisWeek": "Stunden diese Woche",
    "dashboard.ofTarget": "von 40h Ziel",
    "dashboard.vsLastWeek": "ggü. letzter Woche",
    "dashboard.billableHours": "Abrechenbare Stunden",
    "dashboard.billableRate": "Abrechnungsrate",
    "dashboard.pendingApprovals": "Ausstehende Genehmigungen",
    "dashboard.awaitingReview": "Warten auf Prüfung",
    "dashboard.approvedTimesheets": "Genehmigte Stundenzettel",
    "dashboard.thisMonth": "Diesen Monat",
    "dashboard.vsLastMonth": "ggü. letztem Monat",
    "dashboard.recentActivity": "Letzte Aktivität",
    "dashboard.weeklyHours": "Wochenstunden",
    "dashboard.projectsThisWeek": "Projekte diese Woche",
    "dashboard.total": "gesamt",
    "dashboard.upcomingDeadlines": "Kommende Fristen",
    "dashboard.dueToday": "Heute fällig",
    "dashboard.daysLeft": "Tage übrig",
    "dashboard.billable": "Abrechenbar",
    "dashboard.nonBillable": "Nicht abrechenbar",
    
    // Activity types
    "activity.timeLogged": "Zeit erfasst",
    "activity.timesheetApproved": "Stundenzettel genehmigt",
    "activity.timesheetSubmitted": "Stundenzettel eingereicht",
    "activity.entryRequiresChanges": "Eintrag erfordert Änderungen",
    
    // Daily Entry
    "daily.title": "Tägliche Zeiterfassung",
    "daily.subtitle": "Erfassen Sie Ihre Stunden für den Tag",
    "daily.timerRunning": "Timer läuft",
    "daily.startTimer": "Timer starten",
    "daily.start": "Start",
    "daily.stop": "Stopp",
    "daily.copyPreviousDay": "Vortag kopieren",
    "daily.dailyTotal": "Tagessumme",
    "daily.project": "Projekt",
    "daily.description": "Beschreibung",
    "daily.startTime": "Beginn",
    "daily.endTime": "Ende",
    "daily.duration": "Dauer",
    "daily.billableToggle": "Abrechenbar",
    "daily.selectProject": "Projekt wählen",
    "daily.whatDidYouWork": "Woran haben Sie gearbeitet?",
    "daily.addTimeEntry": "Zeiteintrag hinzufügen",
    "daily.entriesLogged": "Einträge erfasst für",
    "daily.saveAsDraft": "Als Entwurf speichern",
    "daily.submitForApproval": "Zur Genehmigung einreichen",
    
    // Weekly Entry
    "weekly.title": "Wöchentliche Zeiterfassung",
    "weekly.subtitle": "Anzeigen und Bearbeiten Ihrer Wochenstunden",
    "weekly.week": "Woche",
    "weekly.today": "Heute",
    "weekly.copyWeek": "Woche kopieren",
    "weekly.weekTotal": "Wochensumme",
    "weekly.addProject": "Projekt hinzufügen",
    "weekly.dailyTotal": "Tagessumme",
    "weekly.billableHours": "Abrechenbare Stunden",
    "weekly.ofTotal": "der Gesamtzeit",
    "weekly.targetProgress": "Zielfortschritt",
    "weekly.status": "Status",
    "weekly.pendingApproval": "Ausstehende Genehmigung",
    "weekly.submitted": "Eingereicht",
    "weekly.projects": "Projekte",
    "weekly.logged": "erfasst",
    "weekly.allEntriesSaved": "Alle Einträge automatisch gespeichert",
    "weekly.submitWeek": "Woche einreichen",
    
    // Approvals
    "approvals.title": "Genehmigungswarteschlange",
    "approvals.subtitle": "Stundenzettel warten auf Ihre Prüfung",
    "approvals.searchPlaceholder": "Nach Name oder Projekt suchen...",
    "approvals.allStatus": "Alle Status",
    "approvals.pending": "Ausstehend",
    "approvals.approved": "Genehmigt",
    "approvals.rejected": "Abgelehnt",
    "approvals.selected": "ausgewählt",
    "approvals.approveAll": "Alle genehmigen",
    "approvals.rejectAll": "Alle ablehnen",
    "approvals.employee": "Mitarbeiter",
    "approvals.period": "Zeitraum",
    "approvals.hours": "Stunden",
    "approvals.projects": "Projekte",
    "approvals.actions": "Aktionen",
    "approvals.billable": "abrechenbar",
    "approvals.timesheetDetails": "Stundenzettel-Details",
    "approvals.reviewSubmission": "Überprüfen Sie die vollständige Einreichung",
    "approvals.totalHours": "Gesamtstunden",
    "approvals.close": "Schließen",
    "approvals.reject": "Ablehnen",
    "approvals.approve": "Genehmigen",
    
    // Reports
    "reports.title": "Berichte",
    "reports.subtitle": "Analysieren Sie Ihre Zeiterfassungsdaten",
    "reports.overview": "Übersicht",
    "reports.byProject": "Nach Projekt",
    "reports.byTeamMember": "Nach Teammitglied",
    "reports.byClient": "Nach Kunde",
    "reports.allProjects": "Alle Projekte",
    "reports.totalHours": "Gesamtstunden",
    "reports.vsPreviousPeriod": "ggü. Vorperiode",
    "reports.billableHours": "Abrechenbare Stunden",
    "reports.billableRate": "Abrechnungsrate",
    "reports.teamMembers": "Teammitglieder",
    "reports.activeThisPeriod": "Aktiv in diesem Zeitraum",
    "reports.avgUtilization": "Durchschn. Auslastung",
    "reports.vsTarget": "ggü. Ziel",
    "reports.monthlyTrends": "Monatliche Trends",
    "reports.timeByProject": "Zeit nach Projekt",
    "reports.teamBreakdown": "Team-Übersicht",
    "reports.teamMember": "Teammitglied",
    "reports.utilization": "Auslastung",
    "reports.progress": "Fortschritt",
    
    // Settings
    "settings.title": "Einstellungen",
    "settings.subtitle": "Verwalten Sie Ihr Konto und Ihre Präferenzen",
    "settings.profile": "Profil",
    "settings.profileDesc": "Ihre persönlichen Informationen",
    "settings.preferences": "Präferenzen",
    "settings.preferencesDesc": "Passen Sie Ihre Erfahrung an",
    "settings.account": "Konto",
    "settings.accountDesc": "Sicherheit und Authentifizierung",
    "settings.appSettings": "App-Einstellungen",
    "settings.appSettingsDesc": "Anwendungskonfiguration",
    "settings.firstName": "Vorname",
    "settings.lastName": "Nachname",
    "settings.email": "E-Mail-Adresse",
    "settings.jobTitle": "Berufsbezeichnung",
    "settings.department": "Abteilung",
    "settings.phone": "Telefonnummer",
    "settings.timezone": "Zeitzone",
    "settings.dateFormat": "Datumsformat",
    "settings.timeFormat": "Zeitformat",
    "settings.weekStartsOn": "Woche beginnt am",
    "settings.monday": "Montag",
    "settings.sunday": "Sonntag",
    "settings.notifications": "Benachrichtigungen",
    "settings.emailNotifications": "E-Mail-Benachrichtigungen",
    "settings.emailNotificationsDesc": "Erhalten Sie E-Mail-Updates zu Ihren Stundenzetteln",
    "settings.reminderNotifications": "Erinnerungsbenachrichtigungen",
    "settings.reminderNotificationsDesc": "Lassen Sie sich an die Einreichung erinnern",
    "settings.approvalNotifications": "Genehmigungsbenachrichtigungen",
    "settings.approvalNotificationsDesc": "Benachrichtigung bei Genehmigung oder Ablehnung",
    "settings.changePassword": "Passwort ändern",
    "settings.currentPassword": "Aktuelles Passwort",
    "settings.newPassword": "Neues Passwort",
    "settings.confirmPassword": "Neues Passwort bestätigen",
    "settings.updatePassword": "Passwort aktualisieren",
    "settings.twoFactorAuth": "Zwei-Faktor-Authentifizierung",
    "settings.twoFactorAuthDesc": "Fügen Sie eine zusätzliche Sicherheitsebene hinzu",
    "settings.enable2FA": "2FA aktivieren",
    "settings.activeSessions": "Aktive Sitzungen",
    "settings.activeSessionsDesc": "Verwalten Sie Ihre angemeldeten Geräte",
    "settings.viewSessions": "Sitzungen anzeigen",
    "settings.defaultProject": "Standardprojekt",
    "settings.selectDefault": "Standard wählen",
    "settings.defaultBillable": "Standard-Abrechnungsstatus",
    "settings.billableByDefault": "Standardmäßig abrechenbar",
    "settings.billableByDefaultDesc": "Neue Zeiteinträge sind standardmäßig abrechenbar",
    "settings.workingHours": "Arbeitszeiten",
    "settings.hoursPerDay": "Stunden pro Tag",
    "settings.hoursPerWeek": "Stunden pro Woche",
    "settings.autoSave": "Automatisches Speichern",
    "settings.autoSaveDesc": "Zeiteinträge automatisch speichern",
    "settings.saveChanges": "Änderungen speichern",
    "settings.dangerZone": "Gefahrenzone",
    "settings.deleteAccount": "Konto löschen",
    "settings.deleteAccountDesc": "Konto und alle Daten dauerhaft löschen",
    
    // Help
    "help.title": "Hilfezentrum",
    "help.subtitle": "Finden Sie Antworten und erhalten Sie Unterstützung",
    "help.searchPlaceholder": "Nach Hilfeartikeln suchen...",
    "help.quickLinks": "Schnellzugriff",
    "help.gettingStarted": "Erste Schritte",
    "help.gettingStartedDesc": "Lernen Sie die Grundlagen der Zeiterfassung",
    "help.videoTutorials": "Video-Tutorials",
    "help.videoTutorialsDesc": "Schauen Sie sich Schritt-für-Schritt-Anleitungen an",
    "help.keyboard": "Tastaturkürzel",
    "help.keyboardDesc": "Arbeiten Sie schneller mit Kürzeln",
    "help.apiDocs": "API-Dokumentation",
    "help.apiDocsDesc": "Integration mit anderen Tools",
    "help.faq": "Häufig gestellte Fragen",
    "help.contactSupport": "Support kontaktieren",
    "help.contactSupportDesc": "Sie finden nicht, was Sie suchen? Unser Support-Team hilft Ihnen gerne.",
    "help.name": "Ihr Name",
    "help.emailAddress": "E-Mail-Adresse",
    "help.subject": "Betreff",
    "help.selectTopic": "Thema wählen",
    "help.generalQuestion": "Allgemeine Frage",
    "help.technicalIssue": "Technisches Problem",
    "help.billingInquiry": "Rechnungsanfrage",
    "help.featureRequest": "Funktionswunsch",
    "help.message": "Nachricht",
    "help.describeIssue": "Beschreiben Sie Ihr Problem oder Ihre Frage...",
    "help.sendMessage": "Nachricht senden",
    
    // FAQ
    "faq.howToLog": "Wie erfasse ich meine Zeit?",
    "faq.howToLogAnswer": "Sie können Zeit auf zwei Arten erfassen: 1) Nutzen Sie die Tageseintrag-Seite, um Ihre Stunden manuell mit Start-/Endzeiten oder Dauer einzugeben. 2) Nutzen Sie die Timer-Funktion zur Echtzeit-Erfassung. Wählen Sie einfach ein Projekt, fügen Sie eine Beschreibung hinzu und klicken Sie auf Start.",
    "faq.editEntry": "Kann ich einen eingereichten Stundenzettel bearbeiten?",
    "faq.editEntryAnswer": "Sobald ein Stundenzettel zur Genehmigung eingereicht wurde, können Sie ihn nicht direkt bearbeiten. Sie können jedoch Ihren Manager bitten, ihn abzulehnen, wodurch er zur Bearbeitung in den Entwurfsstatus zurückkehrt.",
    "faq.billableVsNon": "Was ist der Unterschied zwischen abrechenbaren und nicht abrechenbaren Stunden?",
    "faq.billableVsNonAnswer": "Abrechenbare Stunden sind Zeit, die für Kundenarbeit aufgewendet wird und in Rechnung gestellt werden kann. Nicht abrechenbare Stunden umfassen interne Meetings, Schulungen, administrative Aufgaben und andere Aktivitäten.",
    "faq.approvalTime": "Wie lange dauert die Genehmigung?",
    "faq.approvalTimeAnswer": "Die Genehmigungszeiten variieren je nach Organisation. Typischerweise prüfen Manager Stundenzettel innerhalb von 1-3 Werktagen. Sie erhalten eine Benachrichtigung, wenn Ihr Stundenzettel genehmigt wird.",
    "faq.exportData": "Kann ich meine Zeitdaten exportieren?",
    "faq.exportDataAnswer": "Ja! Gehen Sie zur Berichtsseite und nutzen Sie die Export-Buttons, um Ihre Daten im PDF-, Excel- oder CSV-Format herunterzuladen. Sie können vor dem Export nach Zeitraum, Projekt oder Teammitglied filtern.",
    
    // Common
    "common.search": "Suchen",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.view": "Ansehen",
    "common.loading": "Laden...",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.logTime": "Zeit erfassen",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("timeflow-language");
    return (stored as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("timeflow-language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
